language: java
git:
  depth: 1
jdk:
  - oraclejdk8
dist: trusty
env:  
  global:  
   - DISPLAY=:99.0  
before_install:  
  - sh -e /etc/init.d/xvfb start - sleep 10  
#install:
#  - mvn -P '!swt-unix,swt-windows' -Dmaven.test.skip=true package
#  - mvn help:active-profiles dependency:tree org.apache.maven.plugins:maven-dependency-plugin:3.0.1:tree
#after_success:
#  - unzip -l target/pdf-number-pages-0.0.1-SNAPSHOT-distr-windows.zip
cache:
  directories:
    - $HOME/.m2

