language: java
git:
  depth: 1
jdk:
  - oraclejdk8
dist: trusty
env:  
  global:  
   - DISPLAY=:99.0  
before_install:  
  - sh -e /etc/init.d/xvfb start - sleep 10  
  - git clone --depth=1 https://github.com/oliviercailloux/swt-tools
  - pushd swt-tools
  - mvn install
  - popd
cache:
  directories:
    - $HOME/.m2

